### ISSUE TITLE
Indian Rupee

### ISSUE THREAD

**Issue by jothirams** [kennedyoliveira/alfred-rates#1]
Hello

I don’t see Indian Rupee in the list (surprised though!)

**Comment by kennedyoliveira** [comment]
Thx for your feedback! I'll fix it this week, as soon as a get some free time! Any other think you need to fix or add to the workflow, please tell me!

**Comment by kennedyoliveira** [comment]
@jothirams, Done! Check the new version!

**Comment by jothirams** [comment]
@kennedyoliveira I just updated the workflow. Still I’m not able to see the "Indian Rupee" or INR in the "rates". However, I see inside the workflow folder, you have added the Indian Rupee and the India.png file. It seems something is not working.

**Comment by kennedyoliveira** [comment]
@jothirams, Try to run the rateclear, it'll clear the cache and next time you try to search indian it will load.

**Comment by jothirams** [comment]
It worked!
