### ISSUE TITLE
Not all currencies are available

### ISSUE THREAD

**Issue by durmaze** [kennedyoliveira/alfred-rates#12]
Hi,

i cannot find TRY (Turkish Lira) in the available currency list.

thanx

**Comment by kennedyoliveira** [comment]
@durmaze, hello man, what version are you using?

Because it works fine, try to `rateclear` and after run something with TRY.

Post a feedback after.

**Comment by durmaze** [comment]
Hi,

i did rate update.

it still didnt work. but rateclear did the trick. 

thankx

**Comment by kennedyoliveira** [comment]
Your Welcome!
