### ISSUE TITLE
Error convert into Vietnamese currency

### ISSUE THREAD

**Issue by hungmtuci** [kennedyoliveira/alfred-rates#13]
Hi,

![screen shot 2015-12-18 at 15 17 43](https://cloud.githubusercontent.com/assets/9592449/11898796/db7a43b2-a59a-11e5-82d5-aaecaef68a23.png)

Can you please correct the issue in converting into VND.

Greeting,

Hung

**Comment by kennedyoliveira** [comment]
Hello @hungmtuci!

How are you?

Just fixed the problem, do a `rateupdate` and after run `rateclear` then try to convert again!

**Comment by tentypwtk** [comment]
The same for PLN. Why would 3 letters like PLN be different than USD or GBP?

**Comment by kennedyoliveira** [comment]
Hello! The problem is with charset on the money symbol, just fixed it, do a rateclear and try again! doesn't need to update!

**Comment by tentypwtk** [comment]
Brilliant :) Have a nice day!

**Comment by kennedyoliveira** [comment]
@tentypwtk, thanks, you too! :D
