### ISSUE TITLE
Problem with conversion from IDR

### ISSUE THREAD

**Issue by bronestly** [kennedyoliveira/alfred-rates#14]
![screen shot 2016-02-15 at 15 06 09](https://cloud.githubusercontent.com/assets/2916173/13041831/c7c082bc-d3f5-11e5-8be8-d4ec145cf296.png)

Seems like calculation error since IDR exchange rate is pretty high :)

**Comment by kennedyoliveira** [comment]
Hello @drreen!

I checked and its not a calculation error, at least not from me haha
i use yahoo to fetch the rates and they are returning the rate "0.0001" :s
i'll implement and alternative way of calculating this rate, and will notify you as soon as i finish 

Thx for reporting!

**Comment by kennedyoliveira** [comment]
Hey @drreen, i fixed it!
Check the new version v2.4.3! Run `rateupdate`

![fix](https://cloud.githubusercontent.com/assets/7723330/13133480/a06d539a-d5e2-11e5-8a3b-cb98e33e3b5a.png)

**Comment by kennedyoliveira** [comment]
@drreen, you didn't say anything, i'm closing the issue, since it's appear to be working just fine, if you have any further problem, feel free to open a new one or reopen this.
