### ISSUE TITLE
2.4.3 EUR INR doesn’t work

### ISSUE THREAD

**Issue by jothirams** [kennedyoliveira/alfred-rates#15]
Hello

I updated to 2.4.3 and I see that `1 EUR INR` doesn't work. While the below works

```
1 INR EUR
1 INR USD
1 USD INR
```

The error I get is  "Unable to convert 75.1473 to Decimal"

**Comment by kennedyoliveira** [comment]
Hello @jothirams ! For me is working fine, could you try a `rateclear` and try again? Or maybe reinstall it?
![fullscreen_3_31_16__8_59_pm](https://cloud.githubusercontent.com/assets/7723330/14194301/70fc6c3c-f783-11e5-92e2-9eff5a061ea0.png)

**Comment by kennedyoliveira** [comment]
@jothirams are you still with this problem? Maybe is something with your divisor, did you set it or are you using the default one? See this discussion to understand a little #16

**Comment by jothirams** [comment]
@kennedyoliveira The problem is solved now, after I had restarted my system. Thanks for your help.
