### ISSUE TITLE
Four digits after decimal

### ISSUE THREAD

**Issue by jothirams** [kennedyoliveira/alfred-rates#2]
Hello

I see that you only show 2 digits after decimal. Though it might seem sufficient, it would be better if we have four digits so see a more precise value

Just a reference you can check out this: https://github.com/BigLuck/alfred2-currencyconverter

**Comment by kennedyoliveira** [comment]
@jothirams, Done! Check the new version!

**Comment by jothirams** [comment]
@kennedyoliveira This works!. Thanks.
