### ISSUE TITLE
Mathematical Operations Support

### ISSUE THREAD

**Issue by jothirams** [kennedyoliveira/alfred-rates#3]
It would be great, if the workflow can automatically do 
- Multiplication
- Division
- Addition
- Subtraction

For e.g. 

`rate 349 USD EUR` -> Works
`rate 349*1.06 USD EUR` -> Does not work

Such operations would really help.

**Comment by kennedyoliveira** [comment]
@jothirams, i 'll work on it soon!

**Comment by kennedyoliveira** [comment]
@jothirams, Done!

Checkout the new release!

https://github.com/kennedyoliveira/alfred-rates/releases/tag/v2.3.0

**Comment by jothirams** [comment]
@kennedyoliveira It works! Of course handling spaces and braces would be nice, but one can work with what you have already done.
