### ISSUE TITLE
Number Divider Option "." & ","

### ISSUE THREAD

**Issue by Titanmarcel** [kennedyoliveira/alfred-rates#4]
Could you build a option to set the divider from "." to "," between the rates?

For example when I type "rate 100 eur usd" now it says "113.70". But I would prefer to see it in the european standard format as "113,70".

Would be very nice to see that.

**Comment by kennedyoliveira** [comment]
@Titanmarcel, done, check the new version!

**Comment by Titanmarcel** [comment]
Wow you are a absolute lightning fast developer :) Thank you!

**Comment by kennedyoliveira** [comment]
haha thx! any suggestion or improviment 'll ever be appreciated!
