### ISSUE TITLE
Flag Icon EUR

### ISSUE THREAD

**Issue by Titanmarcel** [kennedyoliveira/alfred-rates#5]
I don't know if you can do that but the flag icon for Euro (EUR) is wrong.
What we see now is the flag of Vatican City: https://en.wikipedia.org/wiki/Vatican_City

The european flag looks like this: https://en.wikipedia.org/wiki/Flag_of_Europe

Would be great to change that.

**Comment by kennedyoliveira** [comment]
@Titanmarcel, i corrected it, checkout the new version using the rateupdate and after updaing run rateclear to clear the caches and load new data!

**Comment by Titanmarcel** [comment]
Wow you are a absolute lightning fast developer :) Thank you!

**Comment by kennedyoliveira** [comment]
haha thx! any suggestion or improviment 'll ever be appreciated!
